name: "Git push for CI builds"
description: "Push to git for CI builds"
inputs:
  files:
    description: "list of files (separated with a space) that should be pushed. Default is all"
    required: false
    default: .
  commit_message:
    description: "The message for the commit, default is 'CI Build'. [skip ci] will be appended"
    required: false
    default: "CI build"
  commit_user:
    description: "The user for the commit which will be set in git config, default is 'CI Build'"
    required: false
    default: "CI build"
  commit_email:
    description: "The email for the commit which will be set in git config, default is 'cibuild@cibuild.com'"
    required: false
    default: "cibuild@cibuild.com"
runs:
  using: "composite"
  steps:
    - run: |
        pwd
        ls -al
        echo "git status:"
        git status
        echo "Running git config"
        git config user.name "${{ inputs.commit_user }}"
        git config user.email "${{ inputs.commit_email }}"
        echo "Adding files"
        git add ${{ inputs.files }}
        echo "Commiting changes"
        git commit -m "${{ inputs.commit_message }} [skip ci]"
        echo "Rebase and push"
        git pull --rebase
        git push

      shell: bash

    
